baseURL = "https://xiao2shiqi.github.io/"
languageCode = 'zh-cn'
title = 'è‚–å«å«çš„ä¸ªäººåšå®¢'
theme = 'PaperMod'
[params]
    subtitle = 'ä¸€ä¸ªå®‰é™å†™å­—âœğŸ»çš„åœ°æ–¹'
    [params.contact]
    email = 'xiaobin.phoenix@gmil.com'
    phone = '+1 202-555-1212'